### PR TITLE
Added ability to move the border of the pullquote to the top of the pull quote

### PR DESCRIPTION
**Pull request by avanrossum**
Love this plugin - and I love the fact that it's open source even more.

I had a client that needed pullquotes that were more in line with the way that Wired magazine does theirs - with the border at the top of the quote, so I made a few changes to the base, and thought you might want to include it in the plugin itself.

It still moves the border to the left if it's on mobile, because while at first I did have it stay on top, it really doesn't look good to do so.

If you're not interested in including these changes, that's fine!  Just thought you might want to have a look!

### CODE REVIEW

**Comment by adamdehaven** [comment]
I can't seem to get your changes to actually render a working example. Do you have a link where you're using your suggested code that I could take a look at?

**Comment by avanrossum** [comment]
Sure! I will send you that soon!

________________________________

**Comment by avanrossum** [comment]
Here you go:

http://www.rundierepeat.com/tpfpq/

**Comment by adamdehaven** [comment]
@avanrossum I edited the behavior a bit (just changed the shortcode attribute to `bordertop` and accepts `true|false`)

Thanks for the feature suggestion! You should receive an update notification in WordPress shortly.

**Comment by avanrossum** [comment]
@adamdehaven no problem at all - you change it however you see fit =D

Glad to contribute! Thanks for keeping it open and receiving input!

**Pull request merged**
